# Pipeline for GitHub Repository only
language: python
branches:
  only:
    - /^((feature)|(bugfix)|(hotfix)|(release))\/.*$/
python:
  - "3.8.3"
install:
  - pip install -r requirements.txt
script: python manage.py test
