version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./manage.py test
          name: Test
  deploy-source:
    executor: python/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ec:98:97:46:86:4e:77:2c:93:b6:71:17:94:ce:8f:3b"
      - run:          
          name: Deploy to Dokku
          command: |
            git config user.email "mateusz@mszczesny.com"
            git config user.name "CircleCI Job"
            ssh-keyscan -t rsa mszczesny.com >> ~/.ssh/known_hosts
            git commit --allow-empty -am "Automatic commit from CircleCI"
            git remote add dokku dokku@mszczesny.com:arthub
            git push -f dokku master

workflows:
  main:
    jobs:
      - build-and-test
      - deploy-source:
          requires: [build-and-test]
          filters:
            branches:
              only:
                - master
